language: node_js
sudo: false
install:
  - npm install npm@2
  - ./node_modules/.bin/npm install
  - cd node_modules/react-date-time-group && npm run prepublish && cd -
node_js:
  - "0.12"
  - "0.10"
script:
  - npm run ci
cache:
  directories:
    - node_modules
